spring:
  main:
    web-application-type: REACTIVE
  cloud:
    function:
      definition: helloFunction
      web:
        export:
          debug: true
debug: true

logging:
  level:
    org:
      springframework:
        cloud:
          function: DEBUG
